name: Example

on:
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Example step
      run: echo "PR title ${{ github.event.pull_request.title }}
